Repository honeycombio/honeycomb-opentelemetry-node, pull requests merged in 2022-11, with the labels that each got.

#104 ci: update publish setup command
  .circleci/config.yml
  .github/workflows/validate-pr-title.yml
Labels: type: bug, version: no bump, no-changelog

#106 test: add smoky expectations for BaggageSpanProcessor
  examples/hello-node-express/index.js
  smoke-tests/smoke-sdk-grpc.bats
  smoke-tests/smoke-sdk-http.bats
Labels: version: no bump, type: maintenance

#108 rel: v0.1.1-beta
  CHANGELOG.md
  package-lock.json
  package.json
Labels: version: no bump, no-changelog

#111 feat: support enum-style protocol specification
  src/honeycomb-options.ts
  test/honeycomb-options.test.ts
Labels: type: enhancement

#114 feat: Export `HoneycombOptions` type
  examples/hello-node-express-ts/index.ts
  examples/hello-node-express-ts/instrumentation.ts
  src/index.ts
Labels: type: enhancement, version: bump minor

#115 rel: v0.2.0-beta
  CHANGELOG.md
  RELEASING.md
  package-lock.json
  package.json
Labels: no-changelog

#116 maint: update release checklist
  RELEASING.md
Labels: version: no bump, type: maintenance, no-changelog

#117 maint: update readme for public beta
  README.md
  src/local-exporter.ts
Labels: version: no bump, type: maintenance, merge at will

#118 ci: add PR comment for failed title check & ignore dependabot PRs
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, version: no bump, no-changelog
