Repository honeycombio/honeycomb-opentelemetry-node, pull requests merged in 2022-12, with the labels that each got.

#127 feat: Add metrics supprt for http/proto
  .eslintrc.js
  examples/hello-node-express-ts/index.ts
  examples/hello-node-express-ts/instrumentation.ts
  examples/hello-node-express-ts/package-lock.json
  examples/hello-node-express-ts/package.json
  package-lock.json
  package.json
  src/exporter-utils.ts
  src/honeycomb-options.ts
  src/http-proto-metrics-exporter.ts
  src/index.ts
  src/opentelemetry-node.ts
  test/exporter-utils.test.ts
  test/http-proto-metrics-exporter.test.ts
  test/setup-jest.ts
Labels: type: enhancement, version: bump minor

#131 fix: add semantic commit prefix to dependabot PRs
  .github/dependabot.yml
Labels: type: bug, version: no bump, no-changelog

#135 fix: dependabot config for scope
  .github/dependabot.yml
Labels: type: bug, version: no bump, no-changelog

#132 chore: add metrics tests to smoke tests
  examples/hello-node-express-ts/index.ts
  examples/hello-node-express-ts/package-lock.json
  examples/hello-node-express-ts/package.json
  examples/hello-node-express/index.js
  examples/hello-node-express/package-lock.json
  examples/hello-node-express/package.json
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-sdk-http-ts.bats
  smoke-tests/smoke-sdk-http.bats
Labels: version: no bump, type: maintenance

#133 refactor: update MetricExporter to be singular to match TraceExporter
  src/exporter-utils.ts
  src/http-proto-metric-exporter.ts
  src/index.ts
  test/http-proto-metric-exporter.test.ts
Labels: version: no bump, type: maintenance

#141 feat: make metrics export configurable
  smoke-tests/docker-compose.yml
  src/exporter-utils.ts
  src/honeycomb-options.ts
  test/honeycomb-options.test.ts
  test/setup-jest.ts
Labels: type: enhancement, version: bump minor
