Repository honeycombio/honeycomb-opentelemetry-node, pull requests merged in 2023-10, with the labels that each got.

#237 maint: add dependabot groups and example deps
  .github/dependabot.yml
Labels: version: no bump, type: maintenance, no-changelog

#241 maint: Bump OTel libraries
  README.md
  RELEASING.md
  examples/hello-node-express-ts/package-lock.json
  examples/hello-node-express-ts/package.json
  examples/hello-node-express/package-lock.json
  examples/hello-node-express/package.json
  examples/hello-node/package-lock.json
  examples/hello-node/package.json
  package-lock.json
  package.json
Labels: version: bump minor, type: maintenance

#243 rel: v0.6.0-beta
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: no-changelog
