Repository honeycombio/honeycomb-opentelemetry-node, pull requests merged in 2023-07, with the labels that each got.

#202 feat: Add option to skip options validation
  src/honeycomb-options.ts
  test/honeycomb-options.test.ts
Labels: type: enhancement, version: bump minor

#204 fix: allow overriding node sdk properties
  src/opentelemetry-node.ts
  test/opentelemetry-node.test.ts
Labels: type: enhancement, version: bump minor, status: oncall

#207 fix: add @opentelemetry/core as a dependency
  package-lock.json
  package.json
Labels: type: bug, status: oncall, version: bump patch

#213 maint: add custom sampler warning
  src/honeycomb-options.ts
  test/honeycomb-options.test.ts
Labels: type: maintenance, version: bump patch

#222 rel: v0.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: version: no bump, type: maintenance, no-changelog
