Repository honeycombio/honeycomb-opentelemetry-node, pull requests merged in 2023-01, with the labels that each got.

#152 fix: Allow user specified resource attributes
  examples/hello-node-express-ts/README.md
  examples/hello-node-express-ts/instrumentation.ts
  examples/hello-node-express/README.md
  examples/hello-node-express/index.js
  src/opentelemetry-node.ts
  src/resource-builder.ts
  test/resource-builder.test.ts
Labels: type: bug, version: bump patch

#155 rel: v0.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: version: no bump, type: maintenance, no-changelog

#150 feat: Add gRPC metrics export support
  package-lock.json
  package.json
  smoke-tests/smoke-sdk-grpc-ts.bats
  smoke-tests/smoke-sdk-grpc.bats
  smoke-tests/smoke-sdk-http-ts.bats
  smoke-tests/smoke-sdk-http.bats
  src/exporter-utils.ts
  src/grpc-metric-exporter.ts
  src/index.ts
  test/exporter-utils.test.ts
  test/grpc-metric-exporter.test.ts
Labels: version: bump minor

#156 rel: Prepare v0.3.2 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: type: maintenance, version: bump patch
