Repository honeycombio/honeycomb-opentelemetry-node, pull requests merged in 2023-12, with the labels that each got.

#254 maint: add deps and docs to maintenance in release
  .github/release.yml
Labels: version: no bump, type: maintenance, no-changelog

#255 maint: update codeowners to pipeline-team
  .github/CODEOWNERS
Labels: type: maintenance

#256 fix: composite exporter is for production use
  src/composite-exporter.ts
Labels: type: maintenance, version: bump patch

#257 maint: more batching of dependabot groups
  .github/dependabot.yml
Labels: version: no bump, type: maintenance
