Repository honeycombio/honeycomb-opentelemetry-node, pull requests merged in 2024-04, with the labels that each got.

#305 rel: prep release v0.7.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: no-changelog

#306 chore: update team for dependabot review
  .github/dependabot.yml
Labels: version: no bump, type: maintenance, merge at will

#313 maint: Update project status and add status link in README
  OSSMETADATA
  README.md
Labels: version: no bump, type: maintenance

#314 maint: Update readme link to sunset issue
  README.md
Labels: version: no bump, type: maintenance, no-changelog
